[package]
name = "cargo-casper"
version = "3.0.0"
authors = ["Jakub Zajkowski <jakub@casper.network>"]
edition = "2021"
description = "A command line tool for creating a Wasm smart contract and tests for use on the Casper network."
documentation = "https://docs.rs/cargo-casper"
readme = "README.md"
homepage = "https://www.casper.network"
repository = "https://github.com/casper-ecosystem/cargo-casper"
license = "Apache-2.0"
include = ["src/*.rs", "Cargo.lock", "Cargo.toml", "resources/*"]

[dependencies]
clap = { version = "4", features = ["cargo", "deprecated", "wrap_help"] }
colour = "2"

[dev-dependencies]
assert_cmd = "2"
reqwest = { version = "0", features = ["blocking"] }
serde_json = "1"
tempfile = "3"
